name: CI

on:
  push:
    branches: [main, prod]

permissions:
  contents: read
  id-token: write

jobs:
  pipeline:
    uses: Mooroon5-CNP/ci-templates/.github/workflows/pipeline.yml@main
    with:
      app_name: "app3-clown-samba"
      app_port: "8080"
      config_repo_url: "https://github.com/Mooroon5-CNP/config-repo"
      target_cloud: "gcp"
    secrets:
      CONFIG_REPO_TOKEN: ${{ secrets.CONFIG_REPO_TOKEN }}
